### ISSUE TITLE
Not able to extract particular field from "MBRecognitionResult*"

### ISSUE THREAD

**Issue by prasoonpuri12** [BlinkID/blinkid-ui-ios#11]
* Framework addition in Project:  Manual.
* Xcode version : 10.1. 
* Language: Objective-C (ARC OFF).
* Device: iPhone8 / iOS(11.1.1)

Hi, 
I am using your new BlinkIDUI sdk  and I can have the list of all the scanned fields from "recognitionResult.resultEntries" like Secondary ID = Jason", "Primary ID = Bourne", "Sex = F", "Date Of Birth = 3/23/83", "Nationality = UAE", "Document Code = P" from the delegate method "- (void)didScanEntireDocumentWithRecognitionResult:(MBRecognitionResult * _Nonnull)recognitionResult successFrame:(UIImage * _Nullable)successFrame". My query is How to get value for particular key like “"Document Code” ?
Regards,
Prasoon

**Comment by jcular** [comment]
Hi @prasoonpuri12,

`resultEntries` is a list of `MBField`s, and every field has a `key` and `value`.
You can filter the `resultEntries` by key that matches `documentCode` key.
List of keys can be found [here](
https://blinkid.github.io/blinkid-ui-ios/Enums/MBFieldKey.html#/c:@M@BlinkIDUI@E@MBFieldKey@MBFieldKeyDocumentCode)

Kind regards,
Jure

**Comment by prasoonpuri12** [comment]
Hi Jure,

I am trying to access the Document Code as below:
recognitionResult.resultEntries[MBFieldKeyDocumentCode];
But it is giving me "Array Index Out Of Range" Exception, Please correct me if I am syntactically wrong as I am not able to find the correct way to pass the key to MBFields Array.

regards,
Prasoon

**Comment by jcular** [comment]
That's because resultEntries is an array not a dictionary,
Use this: 
```
for (MBField *field in recognitionResult.resultEntries) {
        if (field.key == MBFieldKeyDocumentCode) {
            
        }
}
```
I see now that MBField key is missing @objc.

Kind regards,
Jure

**Comment by jcular** [comment]
I've added a commit that adds `@objc` to MBField public properties.
Making it a dictionary might be a better option though.

**Comment by prasoonpuri12** [comment]
Hi Jure,

So @objc is the culprit, because I had followed the above mentioned approach yerterday and I was not able to access key and value properties of the MBFields class.

Thanks a bunch Jure.

regards,
Prasoon

**Comment by prasoonpuri12** [comment]
Yes Making Dictionary is a sensible option as Array is too big and had many unnecessary fields. Can't we typecast the MBRecognitionResult *  or put filter on this MBFields Array by passing a group for example - MBSwitzerlandIdFrontRecognizer or MBUnitedArabEmiratesIdBackRecognizer so it will give the value for keys mentioned in these classes only.

**Comment by jcular** [comment]
Well, currently only the fields from `MBSwitzerlandIdFrontRecognizer` will be in resultEntries if you're scanning  Switzerland front id. You can see [here](https://github.com/BlinkID/blinkid-ui-ios/blob/c1e7cce6772ea8771e33de1b957c32d24d354e19/BlinkIDUI/BlinkIDUI/Scanning/Extractors/MBIDExtractors.swift#L805) what fields are in the result. Although some fields might not contain any value, but those were left on purpose so you can see what values are extracted when you scan the document if you don't want to search for that in the code. 
 We'll switch that to a dictionary, just need to think what would be the best option. Currently, dates are converted to strings but leaving them as dates might be better.
