### ISSUE TITLE
Back image always coming as Nil when trying to scan a US DL.

### ISSUE THREAD

**Issue by ashu1702** [BlinkID/blinkid-ui-ios#35]
When i scan both front and back of the US DL, after the back scan my delegate method didScanEntireDocument gets called. I find the front image in recognitionResult.frontSideDocumentImage but recognitionResult.backSideDocumentImage is always coming as Nil.

Below are my settings : 

MBBlinkSettings.sharedInstance.frameGrabberMode = .successFrames
        MBBlinkSettings.sharedInstance.frameGrabberDelegate = self
        MBBlinkSettings.sharedInstance.initialCountry = MBCountry(supportedCountry: .unitedStatesOfAmerica)
        MBBlinkSettings.sharedInstance.initialDocument = .driverLicense
        
        MBBlinkSettings.sharedInstance.shouldShowCancelButton = false
        MBBlinkSettings.sharedInstance.shouldValidateDocuments = true

**Comment by dCubelic** [comment]
Hi,

you can get back side document image only if the document recognizer supports document image retrieval, which is not the case for USDLs.

Best regards,
Dominik
